---
# - name: Get kubeadmin password
#   ansible.builtin.slurp:
#     path: /home/{{ ansible_user }}/{{ cluster_name }}/auth/kubeadmin-password
#   register: r_slurp_kubeadmin_password

# - name: Get console route
#   environment:
#     KUBECONFIG: /home/{{ ansible_user }}/{{ cluster_name }}/auth/kubeconfig
#   ansible.builtin.command: oc get route -n openshift-console console -o json
#   register: routeconsole
#   retries: 10
#   delay: 30
#   until: routeconsole is succeeded
#   ignore_errors: true

# - name: Get Webconsole URL
#   environment:
#     KUBECONFIG: /home/{{ ansible_user }}/{{ cluster_name }}/auth/kubeconfig
#   ansible.builtin.command: oc whoami --show-console
#   retries: 10
#   delay: 30
#   until: webconsole_url is succeeded
#   register: webconsole_url

- name: Determine API server URL
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: Infrastructure
    name: cluster
    kubeconfig: "{{ hostvars.localhost.output_dir }}/{{ config }}_{{ guid }}_kubeconfig"
  register: r_api
  retries: 30
  delay: 5
  until:
  - r_api.resources | length > 0
  - r_api.resources[0].status is defined
  - r_api.resources[0].status.apiServerURL is defined
  - r_api.resources[0].status.apiServerURL | length > 0

- name: Determine OpenShift Ingress Domain
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
    kubeconfig: "{{ hostvars.localhost.output_dir }}/{{ config }}_{{ guid }}_kubeconfig"
  register: r_ingress
  retries: 30
  delay: 5
  until:
  - r_ingress.resources | length > 0
  - r_ingress.resources[0].spec.domain is defined
  - r_ingress.resources[0].spec.domain | length > 0

- name: Set facts for OpenShift console and API
  ansible.builtin.set_fact:
    openshift_api_url: "{{ r_api.resources[0].status.apiServerURL | urlsplit('hostname') }}"
    openshift_cluster_ingress_domain: "{{ r_ingress.resources[0].spec.domain }}"

- name: Set user data for OpenShift access
  agnosticd.core.agnosticd_user_info:
    data:
      openshift_api_url: "{{ openshift_api_url }}"
      openshift_console_url: "{{ openshift_console_url }}"
      openshift_client_download_url: "{{ openshift_client_download_url }}"
      openshift_cluster_ingress_domain: "{{ openshift_cluster_ingress_domain }}"
      openshift_kubeadmin_password: "{{ openshift_kubeadmin_password }}"
    msg: |-
      OpenShift Console: {{ openshift_console_url }}
      OpenShift API for command line 'oc' client: {{ openshift_api_url }}
      Download oc client from {{ openshift_client_download_url }}
