---
- name: Step 001.1 Deploy Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
  - name: Deploy none cloud_provider debug task
    ansible.builtin.debug:
      msg: Deploy none cloud_provider debug task
