---
- name: Step 005 Post Software
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
  - name: Print stage message
    ansible.builtin.debug:
      msg: "Step 005 Post-Software"

  # Add bastion host to allow access to the FSxN cluster
  - name: Add trident_one bastion host to inventory
    ansible.builtin.add_host:
      name: trident_bastion
      ansible_ssh_common_args: '-F /dev/null -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
      ansible_connection: ssh
      ansible_host: "{{ trident_one.bastion_public_hostname }}"
      ansible_ssh_user: "{{ trident_one.bastion_ssh_user_name }}"
      ansible_ssh_pass: "{{ trident_one.bastion_ssh_password }}"

  - name: Set up S3 Bucket
    ansible.builtin.include_tasks: setup_s3_bucket.yml

  - name: Set up FSxONTAP
    ansible.builtin.include_tasks: setup_fsxontap.yml

  - name: Set up FSxONTAP post install configuration
    ansible.builtin.include_tasks: setup_fsxontap_post_config.yml

  - name: Create AWS credentials profiles on trident-one bastion
    ansible.builtin.include_tasks: setup_aws_profiles.yml

  - name: Deploy Showroom
    ansible.builtin.include_tasks: setup_showroom.yml
