- name: Use block-in-file to create AWS credentials profiles on trident-one bastion
  delegate_to: trident_bastion
  ansible.builtin.blockinfile:
    path: /home/rosa/.aws/credentials
    insertafter: "EOF"
    marker: "# {mark} trident protect cluster prod and dr profiles"
    block: |
      [prod]
      aws_access_key_id={{ trident_one.aws_access_key_id }}
      aws_secret_access_key={{ trident_one.aws_secret_access_key }}
      region={{ trident_one.aws_default_region }}
      [dr]
      aws_access_key_id={{ trident_two.aws_access_key_id }}
      aws_secret_access_key={{ trident_two.aws_secret_access_key }}
      region={{ trident_two.aws_default_region }}
