# Showroom needs specific authentication info set

- name: Get OpenShift API token
  community.okd.openshift_auth:
    host: "{{ trident_one.rosa_openshift_api_url }}"
    username: "{{ trident_one.rosa_openshift_admin_user }}"
    password: "{{ trident_one.rosa_openshift_admin_password }}"
    validate_certs: false
  register: _openshift_auth_results
  retries: 60
  delay: 30
  until:
  - _openshift_auth_results is defined
  - _openshift_auth_results.k8s_auth is defined
  - _openshift_auth_results.k8s_auth.api_key is defined

- name: Get OpenShift Ingress Domain
  kubernetes.core.k8s_info:
    host: "{{ trident_one.rosa_openshift_api_url }}"
    api_key: "{{ _openshift_auth_results.openshift_auth.api_key }}"
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
  retries: 10
  delay: 30
  until:
    - r_ingress_domain.resources is defined
    - r_ingress_domain.resources | length > 0
    - r_ingress_domain.resources[0].spec is defined
    - r_ingress_domain.resources[0].spec.domain is defined
  register: r_ingress_domain

- name: Prepare OpenShift API AuthN facts for showroom
  ansible.builtin.set_fact:
    openshift_cluster_ingress_domain: "{{ r_ingress_domain.resources[0].spec.domain }}"
    ocp4_workload_showroom_openshift_api_token: "{{ _openshift_auth_results.openshift_auth.api_key }}"
    ocp4_workload_showroom_openshift_api_url: "{{ trident_one.rosa_openshift_api_url }}"

- name: Prepare user_data for showroom
  agnosticd.core.agnosticd_user_info:
    data:
      aws_access_key_id: "{{ trident_one.aws_access_key_id }}"
      aws_default_region: "{{ trident_one.aws_default_region }}"
      aws_sandbox_account_id: "{{ trident_one.aws_sandbox_account_id }}"
      aws_secret_access_key: "{{ trident_one.aws_secret_access_key }}"
      bastion_public_hostname: "{{ trident_one.bastion_public_hostname }}"
      bastion_ssh_password: "{{ trident_one.bastion_ssh_password }}"
      bastion_ssh_user_name: "{{ trident_one.bastion_ssh_user_name }}"
      ocp_dr_trident_starting_csv: "{{ ocp_dr_trident_starting_csv }}"
      ocp_dr_trident_helm_chart_version: "{{ ocp_dr_trident_helm_chart_version }}"
      ocp_dr_trident_cli_version: "{{ ocp_dr_trident_cli_version }}"
      rosa_dr_openshift_api_url: "{{ trident_two.rosa_openshift_api_url }}"
      rosa_dr_openshift_console_url: "{{ trident_two.rosa_openshift_console_url }}"
      rosa_dr_openshift_admin_user: "{{ trident_two.rosa_openshift_admin_user }}"
      rosa_dr_openshift_admin_password: "{{ trident_two.rosa_openshift_admin_password }}"
      rosa_prod_openshift_api_url: "{{ trident_one.rosa_openshift_api_url }}"
      rosa_prod_openshift_console_url: "{{ trident_one.rosa_openshift_console_url }}"
      rosa_prod_openshift_admin_user: "{{ trident_one.rosa_openshift_admin_user }}"
      rosa_prod_openshift_admin_password: "{{ trident_one.rosa_openshift_admin_password }}"
      fsxontap_name1: "{{ ocp_dr_trident_fsx_name1 }}"
      fsxontap_name2: "{{ ocp_dr_trident_fsx_name2 }}"
      fsx_admin_password: "{{ _ocp_dr_trident_fsx_admin_password }}"
      svm_admin_password: "{{ _ocp_dr_trident_svm_admin_password }}"

- name: Deploy Showroom
  ansible.builtin.include_role:
    name: agnosticd.core_workloads.ocp4_workload_showroom
