---
- name: Destroy namespaced OpenShift workloads
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - name: Remove namespaced workload in reverse order
    when: workloads | default([]) | length > 0
    block:
    - name: Remove namespaced workload "{{ workload_loop_var | default('None') }}"
      ansible.builtin.include_role:
        name: "{{ workload_loop_var }}"
      vars:
        ACTION: "destroy"
      loop: "{{ workloads | reverse }}"
      loop_control:
        loop_var: workload_loop_var
