---
- name: Workload lifecycle actions
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
  - name: Fail if no action defined
    when: ACTION is not defined or ACTION == ''
    ansible.builtin.fail:
      msg: ACTION must be defined

  - name: Print message
    ansible.builtin.debug:
      msg: "Running workloads to perform {{ ACTION }} is not implemented for namespace config yet."

  # - name: Run Workloads to perform {{ ACTION }}
  #   loop: "{{ workloads }}"
  #   loop_control:
  #     loop_var: __workload
  #     label: "{{ __workload.name }}"
  #   ansible.builtin.include_tasks: run_workload_on_clusters.yml
  #   vars:
  #     ACTION: "{{ ACTION }}"
