---
- name: Step 005 Post Software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - name: Print message
    ansible.builtin.debug:
      msg: "Step 005 Post Software - Namespace workloads deployment completed"
