---
- name: Step 000 Pre Infrastructure
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - name: Print message
    ansible.builtin.debug:
      msg: "Step 000 Pre Infrastructure - No infrastructure needed for namespace-only deployment"
