---
# Sample Variables for Namespace Config
# Copy this file and customize for your deployment

# Basic environment information
cloud_provider: none
config: namespace
guid: test-tt

# List of workloads to deploy
ocp_workloads_namespaced:
  - namespaced_ocp_workload_example

# Output directory for deployment artifacts
output_dir: "/tmp/output_dir/{{ guid }}"
