---
- name: Step 004 Environment specific Software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - name: Print message
    ansible.builtin.debug:
      msg: "Software {{ ACTION | default('provision') }} started for namespace workloads"

- name: Deploy namespaced OpenShift workloads
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - name: Apply namespaced workload "{{ workload_loop_var | default('None') }}"
    when: workloads | default([]) | length > 0
    vars:
      ACTION: "{{ ACTION | default('provision') }}"
    ansible.builtin.include_role:
      name: "{{ workload_loop_var }}"
    loop: "{{ workloads }}"
    loop_control:
      loop_var: workload_loop_var
