---
- name: Add all authorized keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ item.key }}"
    key_options: "{{ item.key_options | default(omit) }}"
  loop: "{{ host_ssh_authorized_keys }}"
