---
- name: Generate an SSH key on the Bastion and configure access on all the hosts
  ansible.builtin.include_tasks: create_bastion_ssh_key_and_access.yml

- name: Generate .ssh/config
  ansible.builtin.template:
    src: "{{ role_path }}/templates/bastion_ssh_config.j2"
    dest: ~/.ssh/config
    mode: u=r,go=

- name: Add GUID to /etc/skel/.bashrc
  ansible.builtin.lineinfile:
    path: /etc/skel/.bashrc
    regexp: "^export GUID"
    line: "export GUID={{ guid }}"

- name: Add GUID to ~{{ ansible_user }}/.bashrc
  ansible.builtin.lineinfile:
    path: "~{{ ansible_user }}/.bashrc"
    regexp: "^export GUID"
    line: "export GUID={{ guid }}"

- name: Add CLOUDUSER to /etc/skel/.bashrc
  ansible.builtin.lineinfile:
    path: /etc/skel/.bashrc
    regexp: "^export CLOUDUSER"
    line: "export CLOUDUSER={{ ansible_user }}"

- name: Add CLOUDUSER to ~{{ ansible_user }}/.bashrc
  ansible.builtin.lineinfile:
    path: "~{{ ansible_user }}/.bashrc"
    regexp: "^export CLOUDUSER"
    line: "export CLOUDUSER={{ ansible_user }}"

- name: Set up student user
  when: bastion_setup_student_user | bool
  ansible.builtin.include_tasks: setup_student_user.yml
