---
- name: Create .aws directory
  ansible.builtin.file:
    path: "~{{ ansible_user }}/.aws"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,go=

- name: Add aws credentials for sandboxes
  when:
  - hostvars.localhost.student_access_key_id | default("") | length > 0
  - hostvars.localhost.student_access_secret_key | default("") | length > 0
  ansible.builtin.blockinfile:
    path: "~{{ ansible_user }}/.aws/credentials"
    create: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rw,go=
    insertbefore: BOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK Student Credentials"
    block: |-
      [default]
      aws_access_key_id = {{ hostvars.localhost.student_access_key_id }}
      aws_secret_access_key = {{ hostvars.localhost.student_secret_access_key }}

# Only use shared account when no student account has been configured
- name: Add aws credentials for shared account
  when:
  - hostvars.localhost.student_access_key_id | default("") | length == 0
  - aws_access_key_id | default("") != ""
  - aws_secret_access_key | default("") != ""
  ansible.builtin.blockinfile:
    state: present
    path: "~{{ ansible_user }}/.aws/credentials"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rw,go=
    create: true
    insertbefore: BOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK Default Credentials"
    block: |-
      [default]
      aws_access_key_id = {{ aws_access_key_id }}
      aws_secret_access_key = {{ aws_secret_access_key }}
