---
hcp_cluster_name: "{{ guid }}"
hcp_ocp_namespace: "{{ sandbox_openshift_namespace | default(config + '-' + guid)}}"
hcp_ssh_authorized_key: "{{ lookup('ansible.builtin.file', hostvars.localhost.ssh_provision_pubkey_path) }}"
