---
- name: Export in-memory inventory to file
  when: agnosticd_inventory_exporter_enable | bool
  ansible.builtin.template:
    dest: >-
      {{- output_dir -}}
      /inventory_
      {{- agnosticd_inventory_exporter_stage
      | default('unknown_stage') -}}.yaml
    src: inventory.yaml.j2
    mode: ug=rw,o=r
