---
- name: Debug workloads and clusters
  ansible.builtin.debug:
    msg: |
      openshift_workload_deployer_clusters: {{ openshift_workload_deployer_clusters }}
      openshift_workload_deployer_workloads: {{ openshift_workload_deployer_workloads }}
    # verbosity: 2

- name: Create cluster lookup dictionary for easier access
  ansible.builtin.set_fact:
    _cluster_configs: "{{ _cluster_configs | default({}) | combine({item.key: item.value}) }}"
  loop: "{{ openshift_workload_deployer_clusters | map('dict2items') | list | flatten }}"

- name: Debug dictionary
  ansible.builtin.debug:
    var: _cluster_configs

- name: Debug list
  ansible.builtin.debug:
    var: openshift_workload_deployer_clusters | map('dict2items') | list

- name: Get cluster information for each cluster
  ansible.builtin.include_tasks: get_cluster_info.yml
  loop: "{{ openshift_workload_deployer_clusters | map('dict2items') | list }}"
  loop_control:
    loop_var: cluster_pair
    label: "Getting info for cluster: {{ cluster_pair[0].key }}"
  vars:
    current_cluster_name: "{{ cluster_pair[0].key }}"
    current_cluster_config: "{{ cluster_pair[0].value }}"
    current_cluster_k8s_auth_host: "{{ current_cluster_config.api_url }}"
    current_cluster_k8s_auth_api_key: "{{ current_cluster_config.api_token }}"
    current_cluster_k8s_auth_verify_ssl: false

- name: Debug final cluster info dictionary
  ansible.builtin.debug:
    msg: "{{ _openshift_workload_deployer_cluster_info }}"

- name: Deploy workloads to clusters
  ansible.builtin.include_tasks: run_workload_on_clusters.yml
  loop: "{{ openshift_workload_deployer_workloads }}"
  loop_control:
    loop_var: workload_item
    label: "{{ workload_item.name }}"
