---
- name: Debug workloads and clusters
  ansible.builtin.debug:
    msg: |
      openshift_workload_deployer_clusters: {{ openshift_workload_deployer_clusters }}
      openshift_workload_deployer_workloads: {{ openshift_workload_deployer_workloads }}
    # verbosity: 2

- name: Create cluster lookup dictionary for easier access
  ansible.builtin.set_fact:
    _cluster_configs: "{{ _cluster_configs | default({}) | combine({item.key: item.value}) }}"
  loop: "{{ openshift_workload_deployer_clusters | map('dict2items') | list | flatten }}"

- name: Debug dictionary
  ansible.builtin.debug:
    var: _cluster_configs

- name: Debug list
  ansible.builtin.debug:
    var: openshift_workload_deployer_clusters | map('dict2items') | list

- name: Get cluster information for each cluster
  ansible.builtin.include_tasks: get_cluster_info.yml
  loop: "{{ openshift_workload_deployer_clusters | map('dict2items') | list }}"
  loop_control:
    loop_var: cluster_pair
    label: "Getting info for cluster: {{ cluster_pair[0].key }}"
  vars:
    current_cluster_name: "{{ cluster_pair[0].key }}"
    current_cluster_config: "{{ cluster_pair[0].value }}"
    current_cluster_k8s_auth_host: "{{ current_cluster_config.api_url }}"
    current_cluster_k8s_auth_api_key: "{{ current_cluster_config.api_token }}"
    current_cluster_k8s_auth_verify_ssl: false

- name: Debug final cluster info dictionary
  ansible.builtin.debug:
    msg: "{{ _openshift_workload_deployer_cluster_info }}"

- name: Deploy workloads to clusters
  ansible.builtin.include_role:
    name: "{{ workload_item.0.name }}"
    apply:
      environment:
        K8S_AUTH_HOST: "{{ _cluster_configs[workload_item.1].api_url }}"
        K8S_AUTH_API_KEY: "{{ _cluster_configs[workload_item.1].api_token }}"
        K8S_AUTH_VERIFY_SSL: false
  loop: "{{ openshift_workload_deployer_workloads | subelements('clusters') }}"
  loop_control:
    loop_var: workload_item
    label: "Role: {{ workload_item.0.name }} on Cluster: {{ workload_item.1 }}"
  vars:
    openshift_api_url: "{{ _openshift_workload_deployer_cluster_info[workload_item.1].api_url }}"
    openshift_console_url: "{{ _openshift_workload_deployer_cluster_info[workload_item.1].console_url }}"
    openshift_cluster_ingress_domain: "{{ _openshift_workload_deployer_cluster_info[workload_item.1].ingress_domain }}"
