---
- name: Delete Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
  - name: Run aws_capacity_reservation
    vars:
      ACTION: destroy
    ansible.builtin.include_role:
      name: agnosticd.cloud_provider_aws.aws_capacity_reservation

  - name: Set facts for ssh provision SSH key
    when: ssh_provision_key_name is undefined
    ansible.builtin.include_role:
      name: infra_create_ssh_provision_key

  - name: Destroy infra AWS keypair
    vars:
      ACTION: destroy
    ansible.builtin.include_role:
      name: agnosticd.cloud_provider_aws.aws_ssh_key

  - name: Run aws_open_environment Role
    when: agnosticd_open_environment | default(false) | bool
    vars:
      ACTION: destroy
    ansible.builtin.include_role:
      name: agnosticd.cloud_provider_aws.aws_open_environment

  - name: Run aws_template_destroy
    ansible.builtin.include_role:
      name: agnosticd.cloud_provider_aws.aws_template_destroy
