---
- name: Delete Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
  - name: Run capacity_reservation
    vars:
      ACTION: destroy
    ansible.builtin.include_role:
      name: agnosticd.cloud_provider_aws.capacity_reservation

  - name: Set facts for ssh provision SSH key
    when: ssh_provision_key_name is undefined
    ansible.builtin.include_role:
      name: infra_create_ssh_provision_key

  - name: Destroy infra AWS keypair
    vars:
      ACTION: destroy
    ansible.builtin.include_role:
      name: agnosticd.cloud_provider_aws.ssh_key

  - name: Run open_environment role
    when: agnosticd_open_environment | default(false) | bool
    vars:
      ACTION: destroy
    ansible.builtin.include_role:
      name: agnosticd.cloud_provider_aws.open_environment

  - name: Run template_destroy
    ansible.builtin.include_role:
      name: agnosticd.cloud_provider_aws.template_destroy
