---
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
  # AWS
  - name: Run aws_create_inventory role
    when: cloud_provider == 'aws'
    ansible.builtin.include_role:
      name: agnosticd.cloud_provider_aws.create_inventory

  # OpenShift CNV
  - name: Run create_inventory role
    when: cloud_provider == 'openshift_cnv'
    ansible.builtin.include_role:
      name: agnosticd.cloud_provider_openshift_cnv.create_inventory

  # Azure
  - name: Azure
    when: cloud_provider == 'azure'
    block:
    - name: Set facts for ssh provision SSH key
      when: ssh_provision_key_name is undefined
      ansible.builtin.include_role:
        name: infra_create_ssh_provision_key

    - name: Locate environment SSH key
      ansible.builtin.include_role:
        name: locate_env_authorized_key

    - name: Azure post start actions
      ansible.builtin.include_role:
        name: infra_azure_create_inventory

- name: Set ansible_ssh_extra_args
  hosts:
  - all:!windows:!network
  gather_facts: false
  any_errors_fatal: true
  ignore_errors: false
  tasks:
  - name: Set facts for remote access
    ansible.builtin.set_fact:
      ansible_ssh_extra_args: >-
        {{ ansible_ssh_extra_args | default() }}
        -F {{ hostvars.localhost.output_dir }}/{{ config }}_{{ guid }}_ssh_conf

- name: Wait for bastion host to be available on start
  hosts: bastions
  run_once: true
  become: false
  gather_facts: false
  tasks:
  - name: Test that the bastion host is available, if not skip approve csr and pod cleanup
    when: ACTION == "start"
    ansible.builtin.wait_for_connection:
      # timeout: 60
      timeout: 1
    register: r_wait
    ignore_errors: true

- name: Run recover cluster actions
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
  - name: Approve CertificateSigningRequests
    when: hostvars[groups['bastions'][0]]['r_wait'] is successful
    ansible.builtin.include_role:
      name: ocp4_approve_certificate_signing_requests
