---
- name: Step 005 - Post software
  hosts: bastions
  become: false
  gather_facts: false
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/{{ cluster_name }}/auth/kubeconfig
  tasks:
  - name: Print post software
    ansible.builtin.debug:
      msg: "Post-Software Steps starting"

  - name: Remove AWS Credentials from bastion
    when: cloud_provider == 'aws'
    ansible.builtin.file:
      path: "/home/{{ ansible_user }}/.aws/credentials"
      state: absent

  - name: Remove Azure Credentials directory from bastion
    when: cloud_provider == 'azure'
    ansible.builtin.file:
      path: "/home/{{ ansible_user }}/.azure"
      state: absent

  - name: Remove the openshift-installer GCP Credentials directory from bastion
    when: cloud_provider == 'gcp'
    ansible.builtin.file:
      path: "/home/{{ ansible_user }}/.gcp"
      state: absent

  - name: Remove gcloud CLI Credentials directory from bastion
    when: cloud_provider == 'gcp'
    ansible.builtin.file:
      path: "/home/{{ ansible_user }}/.config/gcloud"
      state: absent

  - name: Print GCP access user info
    when:
    - cloud_provider == "gcp"
    - agnosticd_open_environment | default(false) | bool
    ansible.builtin.include_role:
      name: open-env-gcp-user-info

- name: Step 005.2 - Post install cluster configuration
  hosts: localhost
  gather_facts: false
  become: false
  environment:
    KUBECONFIG: "{{ hostvars.localhost.output_dir }}/{{ config }}_{{ guid }}_kubeconfig"
  tasks:
  - name: Setup cluster-admin service account
    when: openshift_cluster_admin_service_account_enable | bool
    ansible.builtin.include_role:
      name: openshift_cluster_admin_service_account

- name: Step 005.3 - Deploy Workloads
  ansible.builtin.import_playbook: workloads.yml

# - name: Step 005.4 Clean up Google SDK
#   hosts: localhost
#   gather_facts: false
#   become: false
#   tasks:
#   - name: Remove Google Cloud SDK
#     when: cloud_provider == "gcp"
#     ansible.builtin.file:
#       path: "{{ output_dir }}/google-cloud-sdk"
#       state: absent
