---
- name: Step 003 - Pre Software
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
  - name: Print debug message
    ansible.builtin.debug:
      msg: "Step 003 - Pre Software"

- name: Step 003.1 Configure all hosts with repositories and common packages
  hosts:
  - all:!windows
  become: true
  gather_facts: false
  roles:
  - name: Set up repositories
    when: install_satellite_repositories | bool
    role: host_satellite_repositories

  - name: Install common packages
    when: install_common_packages | bool
    role: host_common_packages

  tasks:
  - name: Add GUID to /etc/skel/.bashrc
    ansible.builtin.lineinfile:
      path: "/etc/skel/.bashrc"
      regexp: "^export GUID"
      line: "export GUID={{ guid }}"

- name: Step 003.2 - Configuring bastion hosts
  hosts: bastions
  become: true
  roles:
  - name: Set up bastion
    when: install_bastion | bool
    role: bastion
