---
roles:
# External role to setup grader host virtualenv and FTL grading infra
- name: ftl-injector
  src: https://github.com/redhat-gpte-devopsautomation/ftl-injector
  version: v0.20.0

# Collections match what's in EE quay.io/agnosticd/ee-multicloud:2025-01-03
collections:
- name: https://github.com/rhpds/assisted_installer.git
  type: git
  version: v0.0.2
