---
# List of Clusters with credentials
# A cluster with name `default` is used when no target clusters are specified for the individual workloads
# openshift_workload_deployer_clusters
# - openshift_app:
#     api_url: ...
#     api_token: ...
#
# - openshift_db:
#     api_url: ...
#     api_token: ...

openshift_workload_deployer_clusters:
- default:
    api_url: "<FROM SECRET>"
    api_token: "<FROM SECRET>"

# List of workloads to apply to clusters with cluster selector
#
# If no clusters are specified then the default cluster is used.
# If clusters are specified cluster names must match a cluster in the list of clusters
#
# openshift_workload_deployer_workloads:
# - name: agnosticd.core_workloads.ocp4_workload_authentication_htpasswd
#   clusters:
#   - openshift_app
#   - openshift_db
# - name: rhpds.mitzi.ocp4_workload_mitzi_app
#   clusters:
#   - openshift_app
# - name: rhpds.mitzi.ocp4_workload_mitzi_db
#   clusters:
#   - openshift_db
#
# Simple example (all workloads deployed to the default cluster):
# openshift_workload_deployer_workloads:
# - agnosticd.core_workloads.ocp4_workload_authentication_htpasswd
# - rhpds.mitzi.ocp4_workload_mitzi_app
# - rhpds.mitzi.ocp4_workload_mitzi_db

openshift_workload_deployer_workloads: []
openshift_workload_deployer_remove_workloads: []
