---
# Control whether to simulate multi-user environment by reporting per-user info messages and data
test_empty_config_multi_user: false
test_empty_config_user_count: "{{ user_count | default(num_users) | default(10) }}"

# Number of hosts to simulate
test_empty_config_host_count: 0
# Size of temporary file generated to simulate host activity.
# Size in count of 1k blocks.
test_empty_config_host_data_size: 1024

# Request config set agnosticd_user_data at top level or per user
#test_empty_config_passthrough_user_data:
#  foo: bar
#test_empty_config_passthrough_per_user_data:
#  foo: bar

# Variables to request the test empty config to fail on specific actions
fail_infra: false
fail_infra_percentage: 0
fail_on_start: false
fail_on_stop: false
fail_post_infra: false
fail_post_software: false
fail_pre_infra: false
fail_pre_software: false
fail_software: false
fail_update: false
...
