---
- name: Step 001 infra
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
    - step001
    - infrastructure
  tasks:

    - name: Entering the test-empty-config infra.yml
      debug:
        msg:
          - Entering the test-empty-config infra.yml

    - when: >-
        fail_infra | bool or
        fail_infra_percentage | int > 100 | ansible.builtin.random
      name: Fail the test-empty-config infra.yml if requested
      fail:
        msg: infra.yml failed as requested

    - when: cloud_provider == 'osp'
      name: Include AWS dry-run read-only role
      include_role:
        name: infra-osp-dry-run

    - when: cloud_provider == 'ec2'
      name: Include AWS dry-run read-only role
      include_role:
        name: infra-aws-dry-run

    - when: cloud_provider == 'equinix_metal'
      name: Include Equinix Metal dry-run read-only role
      include_role:
        name: infra-equinix-metal-dry-run

    - name: Add testhosts
      loop: >-
        {{ range(0, test_empty_config_host_count|int) }}
      loop_control:
        loop_var: testhost_num
        label: "{{ testhost_name }}"
      vars:
        testhost_name: testhost{{ testhost_num }}
      ansible.builtin.add_host:
        name: "{{ testhost_name }}"
        ansible_become: false
        ansible_connection: local
        groups: testhosts
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
        test_empty_config_host_data_size: "{{ test_empty_config_host_data_size }}"

- name: End step 001 infra
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
    - step001
    - infrastructure
  tasks:
    - name: Exiting the test-empty-config infra.yml
      debug:
        msg:
          - Exiting the test-empty-config infra.yml
...
