---
# The type of cloud provider this will be deployed to
cloud_provider: openshift_cnv

# This is the user that Ansible will use to connect to the nodes it is
# configuring from the admin/control host
ansible_user: cloud-user

base_domain: dynamic.redhatworkshops.io

default_instance_image: rhel-9.6
bastion_instance_image: rhel-9.6
# bastion_instance_image: rhel-10.0

#
# Instances to deploy
#
instances:
- name: "{{ bastion_hostname | default('bastion') }}"
  count: 1
  unique: true
  public_dns: false
  dns_loadbalancer: true
  floating_ip: false
  image: "{{ bastion_instance_image | default(default_instance_image) }}"
  memory: 8G
  cores: 4
  image_size: 100Gi
  tags:
  - key: "AnsibleGroup"
    value: "bastions,showroom"
  - key: "ostype"
    value: "linux"
  networks:
  - default
  services:
  - name: bastion
    ports:
    - port: 443
      protocol: TCP
      targetPort: 443
      name: bastion-https
  routes:
  - name: bastion-https
    host: bastion
    service: bastion
    targetPort: 443
    tls: true
...

