---
- name: Gather distribution version
  ansible.builtin.setup:
    gather_subset:
    - distribution_version

# host_ocp4_installer_version = 4.1.1 .. 4.99.99
# host_ocp4_installer_version = 4.x.x-rc.x
# -> specific installer version
- name: Set URLs for OpenShift GA releases (specific version)
  when:
  - not host_ocp4_installer_use_dev_preview | default(false) | bool
  - (host_ocp4_installer_version | string).split('.') | length >= 3
  ansible.builtin.set_fact:
    _host_ocp4_installer_url: >-
      {{ '{0}/ocp/{1}/openshift-install-linux-{1}.tar.gz'.format(
        ocp4_installer_root_url | default("https://mirror.openshift.com/pub/openshift-v4/clients"),
        host_ocp4_installer_version
      ) }}
    _host_ocp4_installer_client_url: >-
      {{ '{0}/ocp/{1}/openshift-client-linux-{1}.tar.gz'.format(
        ocp4_installer_root_url | default("https://mirror.openshift.com/pub/openshift-v4/clients"),
        host_ocp4_installer_version
      ) }}

# host_ocp4_installer_version = 4.1 .. 4.99
# -> latest stable installer for that major version
- name: Set URLs for OpenShift GA releases (latest stable)
  when:
  - not host_ocp4_installer_use_dev_preview | default(false) | bool
  - (host_ocp4_installer_version | string).split('.') | length == 2
  ansible.builtin.set_fact:
    _host_ocp4_installer_url: >-
      {% if ansible_distribution_major_version is version_compare('9', '==') -%}
      {%   if ansible_architecture == 'x86_64' %}
      {{ '{0}/ocp/stable-{1}/openshift-install-rhel9-amd64.tar.gz'.format(
        host_ocp4_installer_root_url | default("https://mirror.openshift.com/pub/openshift-v4/clients"),
        host_ocp4_installer_version
      ) }}
      {%   else %}
      {{ '{0}/ocp/stable-{1}/openshift-install-linux-{2}.tar.gz'.format(
        host_ocp4_installer_root_url | default("https://mirror.openshift.com/pub/openshift-v4/clients"),
        host_ocp4_installer_version,
        ansible_architecture
      ) }}
      {%    endif %}
      {%- else -%}
      {%   if ansible_architecture == 'x86_64' %}
      {{ '{0}/ocp/stable-{1}/openshift-install-linux.tar.gz'.format(
        host_ocp4_installer_root_url | default("https://mirror.openshift.com/pub/openshift-v4/clients"),
        host_ocp4_installer_version
      ) }}
      {%   else %}
      {{ '{0}/ocp/stable-{1}/openshift-install-linux-{2}.tar.gz'.format(
        host_ocp4_installer_root_url | default("https://mirror.openshift.com/pub/openshift-v4/clients"),
        host_ocp4_installer_version,
        ansible_architecture
      ) }}
      {%   endif %}
      {%- endif %}
    _host_ocp4_installer_client_url: >-
      {% if ansible_distribution_major_version is version_compare('9', '==') -%}
      {{ '{0}/ocp/stable-{1}/openshift-client-linux-{2}-rhel9.tar.gz'.format(
        host_ocp4_installer_root_url | default("https://mirror.openshift.com/pub/openshift-v4/clients"),
        host_ocp4_installer_version,
        'amd64' if ansible_architecture == 'x86_64' else ansible_architecture
      ) }}
      {% else %}
      {%   if ansible_architecture == 'x86_64' %}
      {{ '{0}/ocp/stable-{1}/openshift-client-linux.tar.gz'.format(
        host_ocp4_installer_root_url | default("https://mirror.openshift.com/pub/openshift-v4/clients"),
        host_ocp4_installer_version,
        'amd64' if ansible_architecture == 'x86_64' else ansible_architecture
      ) }}
      {%   else %}
      {{ '{0}/ocp/stable-{1}/openshift-client-linux-{2}.tar.gz'.format(
        host_ocp4_installer_root_url | default("https://mirror.openshift.com/pub/openshift-v4/clients"),
        host_ocp4_installer_version,
        ansible_architecture
      ) }}
      {%   endif %}
      {% endif %}

- name: Set URLs for OpenShift dev preview releases
  when: host_ocp4_installer_use_dev_preview | default(false) | bool
  ansible.builtin.set_fact:
    _host_ocp4_installer_url: "{{ host_ocp4_installer_url }}"
    _host_ocp4_installer_client_url: "{{ host_ocp4_client_url }}"

- name: Ensure _host_ocp4_installer_url and _host_ocp4_installer_client_url are set
  ansible.builtin.assert:
    that:
    - _host_ocp4_installer_url | default('') | length > 0
    - _host_ocp4_installer_client_url | default('') | length > 0

- name: Debug URLs
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop:
  - "OpenShift Installer URL: {{ _host_ocp4_installer_url }}"
  - "OpenShift Client URL: {{ _host_ocp4_installer_client_url }}"

- name: Get the OpenShift Installer
  become: true
  ansible.builtin.unarchive:
    src: "{{ _host_ocp4_installer_url }}"
    remote_src: true
    dest: /usr/bin
    mode: ug=rwx,o=rx
    owner: root
    group: root
  register: r_installer
  until: r_installer is success
  retries: 10
  delay: 30

- name: Check if the installer is a FIPS installer
  ansible.builtin.stat:
    path: /usr/bin/openshift-install-fips
  register: r_installer_fips

- name: Hard link the FIPS installer if it exists
  when: r_installer_fips.stat.exists
  become: true
  ansible.builtin.file:
    src: /usr/bin/openshift-install-fips
    dest: /usr/bin/openshift-install
    state: hard
    owner: root
    group: root
    mode: ug,o=rx

- name: Get the OpenShift CLI
  become: true
  ansible.builtin.unarchive:
    src: "{{ _host_ocp4_installer_client_url }}"
    remote_src: true
    dest: /usr/bin
    mode: ug=rwx,o=rx
    owner: root
    group: root
  register: r_client
  until: r_client is success
  retries: 10
  delay: 30
