---
- name: Execute as root
  become: true
  block:
  - name: Setup FIPS mode on the host
    ansible.builtin.command:
      cmd: fips-mode-setup --enable

  - name: Reboot host
    ansible.builtin.reboot:
      msg: Rebooting to enable FIPS mode.
