---
# How to deploy OpenShift
# Valid values are
# - openshift_install
# - openshift_assisted
# - openshift_hcp_cnv
host_ocp4_deploy_installation_method: openshift_install

# Install OpenShift (can be set to false to skip the installation on runs where the cluster already exists)
host_ocp4_deploy_install_ocp4: true
