---
- name: Create dynamic_cache and dynamic_roles directories
  ansible.builtin.file:
    path: "{{ _dir }}"
    state: directory
    mode: ug=rwx,o=rx
  loop:
  - "{{ agnosticd_dynamic_cache_dir }}"
  - "{{ agnosticd_dynamic_roles_dir }}"
  loop_control:
    loop_var: _dir

- name: Install ansible-galaxy sources to dynamic roles dir
  when: _sources != []
  ansible.builtin.include_tasks: install_galaxy_sources_to_dynamic_roles_dir.yml
  vars:
    _sources: >-
      {{ agnosticd_dynamic_role_galaxy_sources | select('agnosticd_dynamic_cache_disabled') | list }}

- name: Install ansible-galaxy sources to cache
  vars:
    _source_name: "{{ _source | agnosticd_dynamic_source_name }}"
    _source_version: "{{ _source | agnosticd_dynamic_source_version }}"
    _source_name_version: "{{ _source_name ~ '-' ~ _source_version }}"
    _source_cache_path: "{{ agnosticd_dynamic_cache_dir }}/{{ _source_name_version }}"
    _requirements_yaml: "{{ agnosticd_dynamic_roles_dir }}/{{ _source_name }}-requirements.yaml"
  ansible.builtin.include_tasks: install_galaxy_source_to_cache.yml
  loop: >-
    {{ agnosticd_dynamic_role_galaxy_sources | select('agnosticd_dynamic_cache_enabled') | list }}
  loop_control:
    loop_var: _source
    label: "{{ _source_name }}"

- name: Install git sources
  vars:
    _source_name: "{{ _source | agnosticd_dynamic_git_source_name }}"
    _install_dir: >-
      {{ agnosticd_dynamic_cache_dir if _source is agnosticd_dynamic_cache_enabled else agnosticd_dynamic_roles_dir }}
    _install_path: >-
      {{ _install_dir }}/{{ _source_name }}
  ansible.builtin.include_tasks: install_git_source.yml
  loop: "{{ agnosticd_dynamic_role_git_sources }}"
  loop_control:
    loop_var: _source
    label: "{{ _source_name }}"
