---
- name: Get the list of installed collections (EE)
  ansible.builtin.command: >-
    ansible-galaxy collection list --format json
  register: r_installed_collections

- name: Create temporary file for requirements.yml (EE)
  ansible.builtin.tempfile:
    state: file
    suffix: requirements
  register: r_tempfile

- name: Rewrite requirements, filter out installed collections (EE)
  vars:
    installed_collections: >-
      {{ r_installed_collections.stdout | from_json }}
  ansible.builtin.copy:
    dest: "{{ r_tempfile.path }}"
    content: >-
      {{ r_requirements_content
      | agnosticd.core.agnosticd_filter_out_installed_collections(installed_collections)
      | to_yaml }}
    mode: ug=rw,o=r

- name: Ensure Cloud provider collection is added to requirements
  when: cloud_provider is defined and cloud_provider | length > 0 and cloud_provider != 'none'
  ansible.builtin.blockinfile:
    path: "{{ r_tempfile.path }}"
    block: |
      # Cloud Provider Collection for {{ cloud_provider }}
      - name: https://github.com/agnosticd/cloud_provider_{{ cloud_provider }}.git
        type: git
        version: {{ cloud_provider_version | default('main') }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - cloud provider collection"
    insertafter: "^collections:"

- name: Read temporary collections file
  ansible.builtin.shell: "cat {{ r_tempfile.path }}"
  register: r_collections_file

- name: Debug contents of temporary collections file
  ansible.builtin.debug:
    msg: |
      {{ item }}
    verbosity: 2
  loop: "{{ r_collections_file.stdout_lines }}"

- name: Get COLLECTIONS_PATHS
  ansible.builtin.set_fact:
    _collections_path: "{{ lookup('config', 'COLLECTIONS_PATHS') }}"

- name: Debug COLLECTIONS_PATHS
  ansible.builtin.debug:
    var: _collections_path
    verbosity: 2

- name: Install collections from requirements.yml (EE)
  vars:
    __collections_path: "{{ lookup('config', 'COLLECTIONS_PATHS')[0] }}"
  ansible.builtin.command: >-
    ansible-galaxy collection install
    --requirements-file "{{ r_tempfile.path }}"
    --collections-path "{{ __collections_path | quote }}"
    --force-with-deps
  register: r_ee_ansible_galaxy_install_collections
  until: r_ee_ansible_galaxy_install_collections is successful
  retries: 5
  delay: 10

- name: Cleanup tempfile (EE)
  ansible.builtin.file:
    path: "{{ r_tempfile.path }}"
    state: absent
