---
# This file is the default playbook for lifecycle actions.
# You should implement those actions in your cloud provider collection if you
# need a specific process.
- name: Run stop/start/status/... actions
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
  - name: Assert guid and config
    when: >-
      guid is not defined or guid == ''
      or config is not defined or config == ''
    ansible.builtin.fail:
      msg: "guid and config must be defined"

  - name: Set default project tag
    when: project_tag is not defined
    ansible.builtin.set_fact:
      project_tag: "{{ config }}-{{ guid }}"

  - name: Fail if ACTION is not defined
    when: ACTION is not defined
    ansible.builtin.fail:
      msg: "ACTION is not defined"

  - name: Print debug statement
    ansible.builtin.debug:
      msg: "Lifecycle called with ACTION: '{{ ACTION }}'"

  - name: Fail when guid is not defined
    when: >-
      guid is not defined
      or guid == ''
      or guid == '*'
    ansible.builtin.fail:
      msg: variable 'guid' must be defined and not empty

  - name: "Include lifecycle tasks for {{ cloud_provider }}"
    ansible.builtin.include_role:
      name: "agnosticd.cloud_provider_{{ cloud_provider }}.lifecycle"
