---
- name: Install extra packages
  ansible.builtin.package:
    state: present
    name: "{{ host_common_packages_extra }}"
  register: r_package
  until: r_package is succeeded
  retries: "{{ host_common_packages_install_retries }}"
  delay: 10
