---
- name: Install common packages for RHEL 10
  ansible.builtin.package:
    state: present
    name: "{{ host_common_packages_el10 }}"
  register: r_package
  until: r_package is succeeded
  retries: "{{ host_common_packages_install_retries }}"
  delay: 10
