---
# The type of cloud provider this will be deployed to
cloud_provider: gcp

# Name of GCP project to manage
project_name: "{{ project_tag }}"
gcp_project_id: "{{ project_tag }}"

# This needs to be created from the gcp_credentials secret (chmod 400)
gcp_credentials_file: '{{ output_dir }}/gcp_credentials_file_{{ guid }}.json'

# Setting a zone
gcp_zone: "{{ gcp_region }}-b"

# This is the user that Ansible will use to connect to the nodes it is
# configuring from the admin/control host
ansible_user: gcpuser
# remote_user: gcpuser

# If we should create DNS delegation or a bastion entry
dns_delegation: false
dns_bastion: true

# GCP region
# gcp_region: us-east1

# -------------------------------------------------------------------
# Instance Variables
# -------------------------------------------------------------------
default_instance_image: rhel-9

default_instance_type: n2-standard-2
# bastion_instance_type: n2-standard-2
# node_instance_type: n2-standard-2
#Disk type for instances for faster disks use pd-ssd or hyperdisk-extreme
disk_type: pd-standard

# -------------------
# Security Groups
# -------------------
security_groups:
  - name: allow-ssh
    from_port: 22
    to_port: 22
    protocol: tcp
    cidr: "0.0.0.0/0"

  - name: allow-http
    from_port: 80
    to_port: 80
    protocol: tcp
    cidr: "0.0.0.0/0"

  - name: allow-https
    from_port: 443
    to_port: 443
    protocol: tcp
    cidr: "0.0.0.0/0"

  - name: allow-vscode
    from_port: 8443
    to_port: 8443
    protocol: tcp
    cidr: "0.0.0.0/0"

  - name: allow-gitea
    from_port: 488
    to_port: 488
    protocol: tcp
    cidr: "0.0.0.0/0"

# -------------------
# Instances
# -------------------
instances:
  - name: "vm"
    image:
      project: rhel-cloud
      family: rhel-9
    flavor:
      gcp: "{{ bastion_instance_type | default(default_instance_type) }}"
    rootfs_size: "{{ bastion_rootfs_size | default(default_rootfs_size) }}"
    # volumes:
    #   - name: disk1
    #     size: 20
    # nested_virtualization: true
    tags:
      - key: "ansiblegroup"
        value: "bastions"
      - key: "ostype"
        value: "linux"
    security_groups:
      - allow-ssh
      - allow-http
      - allow-https
      - allow-vscode
      - allow-gitea

  - name: "node"
    image:
      project: rhel-cloud
      family: rhel-9
    flavor:
      gcp: "{{ node_instance_type | default(default_instance_type) }}"
    tags:
      - key: "ansiblegroup"
        value: "nodes"
      - key: "ostype"
        value: "linux"
    security_groups:
      - allow-ssh
      - allow-http
      - allow-https
