---
- name: Set the query to find the public IPv4 IP of the instance
  ansible.builtin.set_fact:
    find_ip_query: >-
      {%- if cloud_provider == 'vmc' or cloud_provider == 'vmware_ibm' -%}
      localhost.publicips[?name=='{{ _instance_name }}'].ip
      {%- endif -%}

- name: Create DNS
  when: _dns_state == 'present'
  block:
  - name: Print floating IP
    ansible.builtin.debug:
      msg: >-
        The floating IP for {{ _instance_name }}
        is {{ vars[infra_dns_inventory_var] | json_query(find_ip_query) }}

  - name: DNS entry ({{ _dns_state | default('present') }})
    amazon.aws.route53:
      state: present
      aws_access_key_id: "{{ route53_aws_access_key_id }}"
      aws_secret_access_key: "{{ route53_aws_secret_access_key }}"
      hosted_zone_id: "{{ route53_aws_zone_id }}"
      record: "{{ _instance_name }}.{{ guid }}.{{ cluster_dns_zone }}"
      zone: "{{ cluster_dns_zone }}"
      value: "{{ vars[infra_dns_inventory_var] | json_query(find_ip_query) }}"
      type: A
    register: _route53_record
    retries: 10
    delay: "{{ 60 | random(start=5, step=1) }}"
    until: _route53_record is succeeded

  - name: Add public_dns entry to host
    ansible.builtin.add_host:
      name: "{{ _instance_name }}"
      public_dns_name: "{{ _instance_name }}.{{ guid }}.{{ cluster_dns_zone }}"

  - name: DNS alternative entry ({{ _dns_state | default('present') }})
    amazon.aws.route53:
      state: present
      aws_access_key_id: "{{ route53_aws_access_key_id }}"
      aws_secret_access_key: "{{ route53_aws_secret_access_key }}"
      hosted_zone_id: "{{ route53_aws_zone_id }}"
      record: "{{ _alt_name }}{{ _index }}.{{ guid }}.{{ cluster_dns_zone }}"
      zone: "{{ cluster_dns_zone }}"
      value: "{{ vars[infra_dns_inventory_var] | json_query(find_ip_query) }}"
      type: A
    loop: "{{ _alt_names }}"
    loop_control:
      loop_var: _alt_name
    register: _route53_record
    retries: 10
    delay: "{{ 60 | random(start=5, step=1) }}"
    until: _route53_record is succeeded

# When state == absent, don't use inventory var (should not be needed)
- name: Remove DNS
  when: _dns_state == 'absent'
  block:
  - name: DNS entry ({{ _dns_state | default('present') }})
    amazon.aws.route53:
      state: absent
      aws_access_key_id: "{{ route53_aws_access_key_id }}"
      aws_secret_access_key: "{{ route53_aws_secret_access_key }}"
      hosted_zone_id: "{{ route53_aws_zone_id }}"
      record: "{{ _instance_name }}.{{ guid }}.{{ cluster_dns_zone }}"
      zone: "{{ cluster_dns_zone }}"
      type: A
    register: _route53_record
    retries: 10
    delay: "{{ 60 | random(start=5, step=1) }}"
    until: _route53_record is succeeded

  - name: DNS alternative entry ({{ _dns_state | default('present') }})
    amazon.aws.route53:
      state: absent
      aws_access_key_id: "{{ route53_aws_access_key_id }}"
      aws_secret_access_key: "{{ route53_aws_secret_access_key }}"
      hosted_zone_id: "{{ route53_aws_zone_id }}"
      record: "{{ _alt_name }}{{ _index }}.{{ guid }}.{{ cluster_dns_zone }}"
      zone: "{{ cluster_dns_zone }}"
      type: A
    register: _route53_record
    loop: "{{ _alt_names }}"
    loop_control:
      loop_var: _alt_name
    retries: 10
    delay: "{{ 60 | random(start=5, step=1) }}"
    until: _route53_record is succeeded
