---
- name: Step 000 - Pre Infrastructure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
  - name: Print debug message
    ansible.builtin.debug:
      msg: "Step 000 Pre Infrastructure"

# ----------------------------------------------------------------------
# Pre-infra Workloads as role
# ----------------------------------------------------------------------
- name: Import pre-infra workloads
  ansible.builtin.import_playbook: workloads.yml
  vars:
    _workload_title_: "Pre Infra"
    _workloads_: "{{ pre_infra_workloads | default([]) }}"
