---
- name: Set cloud tags
  when: cloud_tags_final is not defined
  ansible.builtin.include_role:
    name: infra_cloud_tags

- name: Set cnv instances array to empty
  ansible.builtin.set_fact:
    r_openshift_cnv_instances: []

- name: Create Instances
  ansible.builtin.include_tasks: create_instance.yaml
  loop: "{{ instances|default([]) }}"
  loop_control:
    loop_var: _instance

- name: Create services for the nodes
  ansible.builtin.include_tasks: create_services.yaml
  loop: "{{ instances|default([]) }}"
  loop_control:
    loop_var: _instance

- name: Create routes for the nodes
  ansible.builtin.include_tasks: create_routes.yaml
  loop: "{{ instances|default([]) }}"
  loop_control:
    loop_var: _instance
