---
- name: Include authentication tasks
  when: sandbox_openshift_username | default(false)
  ansible.builtin.include_tasks: authentication.yaml

- name: Provision actions
  when: ACTION == 'provision'
  module_defaults:
    group/k8s:
      host: "{{ sandbox_openshift_api_url }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key|default(sandbox_openshift_api_key) }}"
      validate_certs: false
  block:
  - name: Create project
    when: sandbox_openshift_namespace is not defined
    ansible.builtin.include_tasks: create_project.yaml

  - name: Create networks
    ansible.builtin.include_tasks: create_networks.yaml

  - name: Create instances
    ansible.builtin.include_tasks: create_instances.yaml

- name: Destroy actions
  when: ACTION == 'destroy'
  module_defaults:
    group/k8s:
      host: "{{ sandbox_openshift_api_url }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key|default(sandbox_openshift_api_key) }}"
      validate_certs: false
  block:
  # Delete a project will delete the VMs, to discuss
  #- ansible.builtin.include_tasks: delete_instances.yaml
  - name: Delete networks
    ansible.builtin.include_tasks: delete_networks.yaml

  - name: Delete project
    when: sandbox_openshift_namespace is not defined
    ansible.builtin.include_tasks: delete_project.yaml

- name: Lifecycle actions
  when: ACTION in ['status', 'start', 'stop']
  module_defaults:
    group/k8s:
      host: "{{ sandbox_openshift_api_url }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key|default(sandbox_openshift_api_key) }}"
      validate_certs: false
  block:
  - name: Include lifecycle tasks
    ansible.builtin.include_tasks: "{{ ACTION }}_instances.yaml"
