---
# ===================================================================
# Additional Collections & roles to be installed for this config
# ===================================================================
# requirements_content:
#   collections:
#   # Core OpenShift Workloads
#   - name: https://github.com/agnosticd/core_workloads.git
#     type: git
#     version: main

# List of Clusters with credentials
# A cluster with name `default` is used when no target clusters are specified for the individual workloads
# clusters
# - openshift_app:
#     api_url: ...
#     api_token: ...
#
# - openshift_db:
#     api_url: ...
#     api_token: ...
clusters:
- default:
    api_url: "<FROM SECRET>"
    api_token: "<FROM SECRET>"

# List of workloads to apply to clusters with cluster selector
#
# If no clusters are specified then the default cluster is used.
# If clusters are specified cluster names must match a cluster in the list of clusters
#
# workloads:
# - name: agnosticd.core_workloads.ocp4_workload_authentication_htpasswd
#   clusters:
#   - openshift_app
#   - openshift_db
# - name: rhpds.mitzi.ocp4_workload_mitzi_app
#   clusters:
#   - openshift_app
# - name: rhpds.mitzi.ocp4_workload_mitzi_db
#   clusters:
#   - openshift_db
#
# Simple example (all workloads deployed to the default cluster):
# workloads:
# - agnosticd.core_workloads.ocp4_workload_authentication_htpasswd
# - rhpds.mitzi.ocp4_workload_mitzi_app
# - rhpds.mitzi.ocp4_workload_mitzi_db

workloads: []
