---
# Variables used to setup authentication if needed.
# openshift_api_ca_cert:
# openshift_api_url:
# openshift_api_key:

# List of workloads to apply to clusters with cluster selector
#
# If clusters are specified then variables must be present matching the cluster
# names with details on how to connect to each cluster.
#
# Ex:
# cluster_workloads:
# - name: ocp4_workload_authentication_htpasswd
#   clusters:
#   - openshift_app
#   - openshift_db
# - name: ocp4_workload_mitzi_app
#   clusters:
#   - openshift_app
# - name: ocp4_workload_mitzi_db
#   clusters:
#   - openshift_db
#
# openshift_app:
#   api_ca_cert: ...
#   api_key: ...
#   api_url: ...
#
# openshift_db:
#   api_ca_cert: ...
#   api_key: ...
#   api_url: ...
cluster_workloads: >-
  {{ openshift_workloads | json_query("[].{name: @, clusters: ['default']}") }}

# Simple list of workloads roles to apply to all clusters
openshift_workloads: >-
  {{ infra_workloads | default([openshift_workload] if openshift_workload is defined else []) }}

target_host: localhost
