---
- name: Destroy workload(s)
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
  - name: Check that remove_workloads is a list
    when: remove_workloads is not defined or remove_workloads is not sequence
    ansible.builtin.fail:
      msg: "remove_workloads variable is either not defined or is not a list"

  - name: Check if workloads is a simple list (no 'clusters' key)
    ansible.builtin.set_fact:
      _workloads_simple_format: >-
        {{ (remove_workloads | length > 0) and (workloads[0].clusters is not defined) }}

  - name: Convert simple format to complex format
    when: _workloads_simple_format
    ansible.builtin.set_fact:
      _workloads: >-
        {{ remove_workloads | json_query("[].{name: name, clusters: ['default']}") }}

  - name: Workloads übernehmen (falls bereits komplexes Format)
    when: not _workloads_simple_format
    ansible.builtin.set_fact:
      _workloads: "{{ workloads }}"

  - name: Destroy Workloads on cluster(s)
    when: remove_workloads | length > 0
    ansible.builtin.include_role:
      name: openshift_workload_deployer
    vars:
      ACTION: destroy
      openshift_workload_deployer_workloads: "{{ _workloads }}"
      openshift_workload_deployer_clusters: "{{ clusters }}"
