---
- name: Step 002 Post Infrastructure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
  - name: Print stage message
    ansible.builtin.debug:
      msg: "Step 002 Post-Infrastructure"
