---
- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
  - name: Call Role to scale OpenShift using Assisted Installer
    when: openshift_cnv_scale_cluster | default(false) | bool
    ansible.builtin.include_role:
      name: host_ocp4_assisted_scale
