---
default_instance_image: rhel-9

# default_instance_type: n2-standard-4
bastion_instance_type: c2-standard-8
node_instance_type: n2-standard-2

# -------------------
# Security Groups
# -------------------
security_groups:
  - name: allow-ssh
    from_port: 22
    to_port: 22
    protocol: tcp
    cidr: "0.0.0.0/0"

  - name: allow-http
    from_port: 80
    to_port: 80
    protocol: tcp
    cidr: "0.0.0.0/0"

  - name: allow-https
    from_port: 443
    to_port: 443
    protocol: tcp
    cidr: "0.0.0.0/0"

# -------------------
# Instances
# -------------------
instances:
  - name: "vm"
    image:
      project: rhel-cloud
      family: rhel-9
    flavor:
      gcp: "{{ bastion_instance_type }}"
    tags:
      - key: "ansiblegroup"
        value: "bastions"
      - key: "ostype"
        value: "linux"
    security_groups:
      - allow-ssh
      - allow-http
      - allow-https

  - name: "node"
    image:
      project: rhel-cloud
      family: rhel-9
    flavor:
      gcp: "{{ node_instance_type }}"
    tags:
      - key: "ansiblegroup"
        value: "nodes"
      - key: "ostype"
        value: "linux"
    security_groups:
      - allow-ssh
      - allow-http
      - allow-https

# -------------------------------------------------------------------
# Workloads
# -------------------------------------------------------------------
pre_infra_workloads:
  localhost:
    - open-env-gcp-add-user-to-project
    - infra-gcp-credentials-file
    - infra-gcp-install-sdk

post_infra_workloads:
  localhost:
    - infra-gcp-ssh-key

pre_software_workloads:
  all:
    - set-repositories
  bastions:
    - common
    - bastion-lite
    - control-user

software_workloads:
  bastions:
    - asset_injector
    - lb1054_image_mode

post_software_final_workloads:
  bastions:
    - showroom

pre_destroy_workloads:
  localhost:
    - create_ssh_provision_key
    - locate_env_authorized_key
    - infra-gcp-credentials-file
    - infra-gcp-install-sdk
    - infra-gcp-ssh-key
    - infra-gcp-create-inventory

post_destroy_workloads:
  localhost:
    - open-env-gcp-remove-project