---

# -------------------------------------------------------------------
# Instance Variables
# -------------------------------------------------------------------
default_instance_image: RHEL94GOLD-latest

default_instance_type: "t3a.large"

default_rootfs_size: 50

# -----------------
# Security Groups
# -----------------
security_groups:
  - name: BastionSG
    rules:
      - name: BastionSSHPorts
        description: "Bastion ssh"
        from_port: 22
        to_port: 22
        protocol: tcp
        cidr: "0.0.0.0/0"
        rule_type: Ingress

  - name: NodeSG
    rules:
      - name: FromNodeSGtcp
        description: "Allow everything from HostSG nodes"
        from_port: 0
        to_port: 65535
        protocol: tcp
        from_group: NodeSG
        rule_type: Ingress

      - name: FromNodeSGudp
        description: "Allow everything from HostSG nodes"
        from_port: 0
        to_port: 65535
        protocol: udp
        from_group: NodeSG
        rule_type: Ingress

# -------------------------------------------------------------------
# Instances
# -------------------------------------------------------------------
instances:
  - name: "bastion"
    count: 1
    unique: true
    public_dns: true
    floating_ip: true
    image: "{{ bastion_instance_image | default(default_instance_image) }}"
    flavor:
      ec2: "{{ bastion_instance_type | default(default_instance_type) }}"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
      - key: "ostype"
        value: "linux"
    rootfs_size: "{{ bastion_rootfs_size | default(default_rootfs_size) }}"
    security_groups:
      - BastionSG
      - NodeSG

  - name: node1
    count: 1
    unique: true
    public_dns: false
    image: "{{ node1_instance_image | default(default_instance_image) }}"
    flavor:
      ec2: "{{ node1_instance_type | default(default_instance_type) }}"
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
      - key: "ostype"
        value: "linux"
    rootfs_size: "{{ node1_rootfs_size | default(default_rootfs_size) }}"
    security_groups:
      - NodeSG

# -------------------------------------------------------------------
# Workloads
# -------------------------------------------------------------------
pre_software_workloads:
  all:
    - set-repositories
  bastions:
    - common
    - bastion-lite
    - control-user

software_workloads:
  bastions:
    - asset_injector

post_software_final_workloads:
  bastions:
    - showroom

